Vote ID Error Handling and Adding Vote Details
curvefi/curve-dao-operations pull request #11
Opened 2023-11-30 20:11 UTC by mo-anon

**What I did:**

- Error Message for Invalid Vote IDs: Fixed error messages when an invalid vote ID is entered (didn't print).
- Vote Information: Added details for each vote, including outcome, voting period, vote counts (yes/no), quorum/support, and execution status.
- Update readme.md: Add output example

<img width="637" alt="285545957-1318d274-068f-40a9-afa2-8c5c845fc06f" src="https://github.com/curvefi/curve-dao-operations/assets/81855630/dfb5bf4a-9286-48a7-886b-f42633670f8a">

2023-12-01 15:23 UTC, chanhosuh commented on curve_dao/vote_utils.py
> +        return False
I don't like returning different types unless forced to.  If `script` is a string, this should return an empty string (although i think it might be some bytes object).  `None` might be ok.

2023-12-01 15:31 UTC, chanhosuh commented on curve_dao/vote_utils.py
> +        return False
As for the try/except logic, shouldn't be catching such a broad exception.  

`getVote` on the aragon contract will raise `ape.exceptions.ContractLogicError: VOTING_NO_VOTE` if it fails with missing vote (which is what you log outside the function where it's used).  Until other exception types are identified, you can just catch the ape error using `except ContractLogicError as e`, parse the error message for the `NO_VOTE`, reraise with a custom exception `MissingVote` and then just catch that outside.

2023-12-13 17:43 UTC, chanhosuh commented on curve_dao/vote_utils.py
> +    pass
very nitpicky: you don't need a `pass` cuz the docstring takes care of the syntax requirement

2023-12-13 17:44 UTC, chanhosuh commented on curve_dao/vote_utils.py
> +            raise MissingVote(f"Vote ID {vote_id} not found")
should re-raise if you can't identify the error

2023-12-13 17:46 UTC, chanhosuh commented on curve_dao/vote_utils.py
> +    if data[3]:  # Voting is ongoing
re: comment on using a dict instead

2023-12-13 17:51 UTC, chanhosuh requested changes
There should be tests for `get_vote_data` and `decode_vote_data`.  Doesn't have to be fancy, can be just something like the tests for `decode_vote` that exercises the main code paths.

2023-12-14 22:02 UTC, chanhosuh approved these changes

2024-01-16 13:39 UTC, bout3fiddy approved these changes

2024-01-16 13:39 UTC, merged